package com.gsmzzk.mapper;

import com.gsmzzk.pojo.Baseinfo;
import com.gsmzzk.pojo.Qualityinfo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface QualityinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qualityinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qualityinfo
     *
     * @mbg.generated
     */
    int insert(Qualityinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qualityinfo
     *
     * @mbg.generated
     */
    Qualityinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qualityinfo
     *
     * @mbg.generated
     */
    List<Qualityinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qualityinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Qualityinfo record);

    public List<Qualityinfo> findByIds(@Param("ids")List<String> idList);
}